# Generated by Django 4.0.10 on 2023-11-28 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidas_actuales', models.IntegerField(default=5)),
                ('vidas_totales_gastadas', models.IntegerField(default=0)),
                ('oro_recolectado', models.IntegerField(default=0)),
                ('mayor_oro_en_una_partida', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='godotapp.usuario')),
            ],
        ),
    ]
