# Generated by Django 4.2.7 on 2023-12-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticasjuego',
            name='vidas_actuales',
            field=models.IntegerField(default=15),
        ),
    ]
