# Generated by Django 4.2.7 on 2023-12-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('godotapp', '0003_estadisticasjuego_oro_total_recolectado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticasjuego',
            old_name='oro_total_recolectado',
            new_name='oro_recolectado_total',
        ),
    ]
